/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MediaPanel.java
 *
 * Created on Mar 28, 2013, 11:30:12 AM
 */

package mediaplayer;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.net.URL;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.NoPlayerException;
import javax.media.Player;

/**
 *
 * @author mahasiswa
 */
public class MediaPanel extends javax.swing.JPanel {

    /** Creates new form MediaPanel */
    public MediaPanel() {
        initComponents();
    }

    public MediaPanel( URL mediaURL ) throws IOException {
    setLayout( new BorderLayout() );
    Manager.setHint( Manager.LIGHTWEIGHT_RENDERER, true );
    try {
    // create a player to play the media specified in the URL
    Player mediaPlayer = Manager.createRealizedPlayer( mediaURL );
    // get the components for the video and the playback controls
    Component video = mediaPlayer.getVisualComponent();
    Component controls = mediaPlayer.getControlPanelComponent();
    if ( video != null )
    add( video, BorderLayout.CENTER );
    if ( controls != null )
    add( controls, BorderLayout.SOUTH );
    mediaPlayer.start(); // start playing the media clip
    } catch ( NoPlayerException noPlayerException ) {
    System.err.println( "No media player found" );
    } catch ( CannotRealizeException cannotRealizeException ) {
    System.err.println( "Could not realize media player" );
    } catch ( IOException iOException ) {
    System.err.println( "Error reading from the source" );
    }
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
